package pl.bratosz.smartlockers.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.HashMap;
import java.util.Map;


public enum ClothName {
    TROUSERS_FEMALE_GRAY_NEW_MAGNA("SPODNIE DAMSKIE-NOWE-MAGNA SZARE", 1051),
    TROUSERS_ASHEN("SPODNIE POPIELATE", 5302),
    TROUSERS_FEMALE_GRAY("SPODNIE DAMSKIE SZARE", 9109),
    TROUSERS_MALE_GRAY_WITH_BAND("SPODNIE MĘSKIE NA GUMCE SZARE", 1052),
    SWEATSHIRT_BLACK("BLUZA CZARNA", 1344),
    OVERALLS_BLACK("OGRODNICZKI CZARNE", 1345),
    OVERALLS_GRAY("OGRODNICZKI SZARE", 1351),
    OVERALLS_INSULATED_NAVY_BLUE("OGRODNICZKI OCIEPLANE GRANATOWE", 3214),
    SWEATSHIRT_WORK_GRAY("BLUZA ROBOCZA SZARA", 1350),
    SWEATSHIRT_SHORT_DARK_GREYT("BLUZA DO PASA CIEMNOSZARA", 1365),
    TROUSERS_KEGEL_BLACK("SPODNIE DO PASA KEGEL CZARNE", 1616),
    APRON_BLUE("FARTUSZEK NIEBIESKI", 1662),
    APRON_FEMALE_GRAY("FARTUCH SZARY DAMSKI", 1366),
    TSHIRT_MALE_BLEND_GRAY("T-SHIRT MĘSKI MELANŻ", 1828),
    TSHIRT_WHITE("T-SHIRT BIAŁY", 5011),
    TSHIRT_BLACK("T-SHIRT CZARNY", 5012),
    TSHIRT_GREEN("T-SHIRT ZIELONY", 5013),
    TSHIRT_RED("T-SHIRT CZERWONY", 5014),
    TSHIRT_YELLOW("T-SHIRT ŻÓŁTY", 5016),
    TSHIRT_BLUE("T-SHIRT NIEBIESKI", 5017),
    TSHIRT_NAVY_BLUE("T-SHIRT GRANATOWY", 5018),
    TSHIRT_DARK_GRAY("T-SHIRT CIEMNOSZARY", 5019),
    TSHIRT_FEMALE_BLEND_GRAY("T-SHIRT DAMSKI SZARY MELANŻ", 5099),
    TSHIRT_FEMALE_BLUE("T-SHIRT DAMSKI NIEBIESKI", 5115),
    TSHIRT_MALE_BLUE_LEAR("T-SHIRT MĘSKI LEAR NIEBIESKI", 5116),
    TSHIRT_BROWN("T-SHIRT BRĄZOWY", 5999),
    POLO_YELLOW("POLO ŻÓŁTE", 5064),
    POLO_WHITE("POLO BIAŁE", 5070),
    POLO_PRINTER_WHITE("POLO PRINTER BIAŁE", 5148),
    POLO_HARVEST_BLACK("POLO HARVEST CZARNE", 5071),
    POLO_RED("POLO CZERWONE", 5072),
    POLO_BLUE("POLO NIEBIESKIE", 5073),
    POLO_GRAY("POLO SZARE", 5074),
    POLO_GREEN("POLO ZIELONE", 5075),
    TROUSERS_WELDING("SPODNIE SPAWALNICZE DO PASA", 5595),
    OVERALLS_WELDING_NAVY_BLUE("OGRODNICZKI SPAWALNICZE GRANATOWE", 6595),
    SWEATSHIRT_WELDING_NAVY_BLUE("BLUZA SPAWALNICZA GRANATOWA", 3595),
    TSHIRT_WELDING_LONG_SLEEVE("T-SHIRT SPAWALNICZY DŁ. RĘKAW", 3526),
    TSHIRT_LONG_SLEEVE_BLACK("T-SHIRT CZARNY DŁ. RĘKAW", 5077),
    JACKET_COALA_NAVY_BLUE("KURTKA KOALA GRANATOWA", 3208),
    HAT_FLEECE_BLACK("CZAPKA CZANRA POLAROWA", 1295),
    TEST_TROUSERS_MALE("SPODNIE MĘSKIE TESTOWE", 2010),
    TEST_POLO_HIGH_VISIBILITY("POLO ODBLASKOWE TESTOWE", 4790);


    private final String name;
    private final Integer articleNo;
    private static final Map<Integer, ClothName>
            articlesByNumbers = new HashMap<>();

    static {
        for (ClothName cloth : ClothName.values()) {
            articlesByNumbers.put(cloth.articleNo, cloth);
        }
    }

    ClothName(String name, Integer articleNo) {
        this.name = name;
        this.articleNo = articleNo;
    }

    public static ClothName getByArticleNo(int articleNo) {
        return articlesByNumbers.get(articleNo);
    }

    @JsonValue
    public String getName() {
        return name;
    }

    public Integer getArticleNo() {
        return articleNo;
    }


}
